# Generated by Django 4.0.6 on 2022-07-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=35, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('chi', models.FloatField(verbose_name='语文')),
                ('math', models.FloatField(verbose_name='数学')),
                ('enf', models.FloatField(verbose_name='英语')),
                ('describe', models.TextField(verbose_name='描述')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
    ]
